services:
  - type: web
    name: dpd-telegram-bot
    env: python
    region: frankfurt
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: python dpd_bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true
    plan: free
